num1=int(input("enter the nummber 1"))
num2=int(input("enter the number 2"))
operator =input("enter the operator")
if operator == "+":
    print(num1+num2)
elif operator=="-":
    print(num1-num2)
elif operator=="*":
    print(num1*num2)
elif operator=="/":
    print(num1/num2)
else:
    print("invalid operator")

    #  thank you for using this calculator      
                    #   THANK YOU 
    #  THIS CODE WAS WRITTEN BY ME NO COPYING 